"""empty message

Revision ID: 02225fe46dad
Revises: 0e9f5d11d872
Create Date: 2020-01-15 10:12:41.646963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02225fe46dad'
down_revision = '0e9f5d11d872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('payment_confirmation', sa.String(length=20), nullable=True))
    op.drop_column('purchase', 'payment_confrimation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('payment_confrimation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('purchase', 'payment_confirmation')
    # ### end Alembic commands ###
