"""empty message

Revision ID: 1fa0e1c5db32
Revises: 02225fe46dad
Create Date: 2020-01-15 10:16:47.506073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa0e1c5db32'
down_revision = '02225fe46dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('hidden_field', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'hidden_field')
    # ### end Alembic commands ###
