"""empty message

Revision ID: e5d0774f5e0e
Revises: 1fa0e1c5db32
Create Date: 2020-01-15 10:17:50.182359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d0774f5e0e'
down_revision = '1fa0e1c5db32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'hidden_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('hidden_field', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
