from os import getenv

FLASK_APP=getenv("FLASK_APP")
FLASK_DEBUG=getenv("FLASK_DEBUG")
FLASK_ADMIN_SWATCH=getenv("FLASK_ADMIN_SWATCH")
SQLALCHEMY_DATABASE_URI=getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = getenv("SECRET_KEY")
